# Generated by Django 3.2.5 on 2021-07-30 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an artwork genre (e.g. Science Fiction)', max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the artwork', max_length=128)),
                ('slug', models.CharField(help_text='The slug of the artwork title', max_length=128, unique=True)),
                ('url', models.CharField(help_text='Relative path to the image', max_length=255)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(help_text='Select a genre for this artwork', to='gallery.Genre')),
            ],
            options={
                'verbose_name_plural': 'Artworks',
                'ordering': ['-published_at'],
            },
        ),
    ]
